# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Data Advocate
tagline:             'Assessing Benefits of Correct Data'
description:         'A Look into Data Inefficiencies within Citrus County, FL'
url:                 http://lanyon.getpoole.com
baseurl:             '/DataAdvocate'
paginate:            5

# About/contact
author:
  name:              Amy E. Hyler
  url:               
  email:             ahyler@mail.usf.edu

# Custom vars
version:             1.0.0
