# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Data Advocate
tagline:             'Assessing Benefits of Correct Data'
description:         <a href="http://gis.citrusbocc.com/index.html" target="_blank"><img src="http://i67.tinypic.com/30rmjrm.png" border="0" alt="Image and video hosting by TinyPic"></a>
                     Advocating for Hydrological Data Efficiencies in Citrus County, FL
url:                 http://lanyon.getpoole.com
baseurl:             '/DataAdvocate'
analysis:            '/DataAdvocate/Analysis.md/

paginate:            5

# About/contact
author:
  name:              Amy E. Hyler
  url:               
  email:             ahyler@mail.usf.edu

# Custom vars
version:             1.0.0
